# Generated by Django 4.0.5 on 2022-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/resumes'),
        ),
    ]
